FROM python:3.8-slim

WORKDIR /ToDoList

COPY . /ToDoList

RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    libpq-dev
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
